import { Film } from "store/state";

export const films: Film[] = [
  {
    adult: false,
    backdropPath: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
    genreIds: [12, 14],
    id: 671,
    originalLanguage: "en",
    originalTitle: "Harry Potter and the Philosopher's Stone",
    overview:
      "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
    popularity: 124.721,
    posterPath: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    releaseDate: "2001-11-16",
    title: "Harry Potter and the Philosopher's Stone",
    video: false,
    voteAverage: 7.9,
    voteCount: 20213,
  },
  {
    adult: false,
    backdropPath: "/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg",
    genreIds: [12, 14, 10751],
    id: 674,
    originalLanguage: "en",
    originalTitle: "Harry Potter and the Goblet of Fire",
    overview:
      "When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools — the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named. In this fourth film adaptation of J.K. Rowling's Harry Potter series, everything changes as Harry, Ron and Hermione leave childhood forever and take on challenges greater than anything they could have imagined.",
    popularity: 106.632,
    posterPath: "/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg",
    releaseDate: "2005-11-16",
    title: "Harry Potter and the Goblet of Fire",
    video: false,
    voteAverage: 7.8,
    voteCount: 15487,
  },
  {
    adult: false,
    backdropPath: "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    genreIds: [28, 878],
    id: 603,
    originalLanguage: "en",
    originalTitle: "The Matrix",
    overview:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    popularity: 39.044,
    posterPath: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    releaseDate: "1999-03-30",
    title: "The Matrix",
    video: false,
    voteAverage: 8.2,
    voteCount: 19157,
  },
  {
    adult: false,
    backdropPath: "/t9dumNakkt6yL9wreEp35T4Lwny.jpg",
    genreIds: [12, 28, 53, 878],
    id: 605,
    originalLanguage: "en",
    originalTitle: "The Matrix Revolutions",
    overview:
      "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
    popularity: 20.488,
    posterPath: "/fgm8OZ7o4G1G1I9EeGcb85Noe6L.jpg",
    releaseDate: "2003-11-03",
    title: "The Matrix Revolutions",
    video: false,
    voteAverage: 6.7,
    voteCount: 6998,
  },
  {
    adult: false,
    backdropPath: "/u9xtjq0oUTWNaYpPPesPPAUt1Y4.jpg",
    genreIds: [28, 35],
    id: 2330,
    originalLanguage: "fr",
    originalTitle: "Taxi",
    overview:
      "In Marseilles (France), skilled pizza delivery boy Daniel who drives a scooter finally has his dreams come true. He gets a taxi license. Caught by the police for a huge speed infraction, he will help Emilien, a loser inspector who can't drive, on the track of German bank robbers, so he doesn't lose his license and his dream job.",
    popularity: 18.546,
    posterPath: "/egBxj3ude84theXc3cLbBHrWOkQ.jpg",
    releaseDate: "1998-04-08",
    title: "Taxi",
    video: false,
    voteAverage: 6.6,
    voteCount: 1676,
  },
  {
    adult: false,
    backdropPath: "/xUPnozC1MpGGWAVeIHwQMZUggM6.jpg",
    genreIds: [35],
    id: 233063,
    originalLanguage: "de",
    originalTitle: "Fack ju Göhte",
    overview:
      "A comedy that follows an ex-con who lands a position at a school that sits over the spot where money from one of his earlier robberies was stashed.",
    popularity: 12.642,
    posterPath: "/hV88MiailtnGVF6rbp6Ug6UBKYS.jpg",
    releaseDate: "2013-11-07",
    title: "Suck Me Shakespeer",
    video: false,
    voteAverage: 7.1,
    voteCount: 1333,
  },
];
